"""
GTTL implementation of SW creates many output files depends on the number of threads. This scripts combines the files and parses them to obtain a tsv file.
Parameter:
- indir: the directory containing all tsv generated by GTTL sw_all_against_all
- target_fasta and query_fasta: FASTA files for target and query db
- outfile: file to write output into
"""

import sys
from pathlib import Path
from Bio import SeqIO


def get_file_list(indir):
    d = Path(indir)
    file_list = list(d.glob("*.tsv"))
    return file_list


def pad_aln(aln, start, length):
    assert (length >= start + len(aln))
    padded = [0] * start + aln + [0] * (length - start - len(aln))
    assert (len(padded) == length)
    return padded


total = 0
for i in range(1):
    # python /scratch/stud2018/ata/ma_scripts/gttl_parser.py 3m_3m_10k/out/1/ 3m_3m_10k/t/tmp_1_10000.fasta 3m_3m_10k/q/tmp_1_10000.fasta 3m_3m_10k/parsed/1.txt
    indir = sys.argv[1]
    target_fasta = sys.argv[2]
    query_fasta = sys.argv[3]
    outfile = sys.argv[4] + f'{i}_header.txt'
    print("Processing")
    print(indir, target_fasta, query_fasta, outfile)
    file_list = get_file_list(indir)
    out = []
    tfasta = SeqIO.index(target_fasta, "fasta")
    t_ids = list(tfasta.keys())
    qfasta = SeqIO.index(query_fasta, "fasta")
    q_ids = list(qfasta.keys())
    for file in file_list:
        with open(file, "r") as handler:
            target_seq = None
            query_seq = None
            tstart = None
            tlen = None
            qstart = None
            qlen = None
            score = None
            bitscore = None
            identity = None
            taln = ""
            qaln = ""
            target_length = None
            query_length = None
            ta = None
            qa = None
            for i, line in enumerate(handler):
                tab_split = line[:-1].split("\t")
                if len(tab_split) == 9:
                    if target_seq is not None:
                        tseq = str(tfasta[t_ids[int(target_seq)]].seq)
                        tsubseq = tseq[int(tstart):int(tstart)+int(tlen)]
                        assert (tsubseq == taln.replace('-', ''))
                        qseq = str(qfasta[q_ids[int(query_seq)]].seq)
                        qsubseq = qseq[int(qstart):int(qstart)+int(qlen)]
                        assert (qsubseq == qaln.replace('-', ''))
                        assert (len(taln) == len(qaln))
                        taln_transformed = [
                            1 if qaln[i] != '-' else 0 for i, c in enumerate(taln) if c != '-']
                        qaln_transformed = [
                            1 if taln[i] != '-' else 0 for i, c in enumerate(qaln) if c != '-']
                        assert (len(taln_transformed) == int(tlen))
                        assert (len(qaln_transformed) == int(qlen))
                        target_length = len(tseq)
                        query_length = len(qseq)
                        taln1 = pad_aln(taln_transformed,
                                        int(tstart), target_length)
                        qaln1 = pad_aln(qaln_transformed,
                                        int(qstart), query_length)
                        assert (sum(taln1) == sum(qaln1))
                        ta = ''.join((str(c) for c in pad_aln(
                            taln_transformed, int(tstart), target_length)))
                        qa = ''.join((str(c) for c in pad_aln(
                            qaln_transformed, int(qstart), query_length)))
                        # out.append([target_seq, query_seq, tstart, tlen, qstart, qlen, score, bitscore, identity, ta, qa])
                        out.append([t_ids[int(target_seq)], q_ids[int(
                            query_seq)], tstart, tlen, qstart, qlen, score, bitscore, identity, ta, qa])
                    target_seq, query_seq, tstart, tlen, qstart, qlen, score, bitscore, identity = tab_split
                    taln = ""
                    qaln = ""
                else:
                    split = line[:-1].split("  ")
                    if split[0] == 'Sbjct':
                        taln += split[-2].strip()
                    elif split[0] == 'Query':
                        qaln += split[-2].strip()

                '''if i % 5 == 0:
                    split = line[:-1].split("\t")
                    print(i, len(split), split)
                    assert(len(split) == 9)
                    target_seq, query_seq, tstart, tlen, qstart, qlen, score, bitscore, identity = split
                    mismatch1 = False
                    mismatch2 = False
                elif i % 5 == 1:
                    split = line[:-1].split("  ")
                    tseq = str(tfasta[t_ids[int(target_seq)]].seq)
                    tsubseq = tseq[int(tstart):int(tstart)+int(tlen)]
                    #assert(tsubseq == split[-2].strip().replace('-',''))
                    taln = split[-2].strip()
                    target_length = len(tseq)
                elif i % 5 == 2:
                    continue
                elif i % 5 == 3:
                    split = line[:-1].split("  ")
                    qseq = str(qfasta[q_ids[int(query_seq)]].seq)
                    qsubseq = qseq[int(qstart):int(qstart)+int(qlen)]
                    #assert(qsubseq == split[-2].strip().replace('-',''))
                    qaln = split[-2].strip()
                    query_length = len(qseq)
                else:
                    assert(len(taln) == len(qaln))
                    taln_transformed = [1 if qaln[i] != '-' else 0 for i,c in enumerate(taln) if c != '-']
                    qaln_transformed = [1 if taln[i] != '-' else 0 for i,c in enumerate(qaln) if c != '-']
                    #assert(len(taln_transformed) == int(tlen))
                    #assert(len(qaln_transformed) == int(qlen))
                    ta = ''.join((str(c) for c in pad_aln(taln_transformed, int(tstart), target_length)))
                    qa = ''.join((str(c) for c in pad_aln(qaln_transformed, int(qstart), query_length)))
                    out.append([target_seq, query_seq, tstart, tlen, qstart, qlen, score, bitscore, identity, ta, qa])'''
            tseq = str(tfasta[t_ids[int(target_seq)]].seq)
            tsubseq = tseq[int(tstart):int(tstart)+int(tlen)]
            assert (tsubseq == taln.replace('-', ''))
            qseq = str(qfasta[q_ids[int(query_seq)]].seq)
            qsubseq = qseq[int(qstart):int(qstart)+int(qlen)]
            assert (qsubseq == qaln.replace('-', ''))
            assert (len(taln) == len(qaln))
            taln_transformed = [
                1 if qaln[i] != '-' else 0 for i, c in enumerate(taln) if c != '-']
            qaln_transformed = [
                1 if taln[i] != '-' else 0 for i, c in enumerate(qaln) if c != '-']
            assert (len(taln_transformed) == int(tlen))
            assert (len(qaln_transformed) == int(qlen))
            target_length = len(tseq)
            query_length = len(qseq)
            taln1 = pad_aln(taln_transformed, int(tstart), target_length)
            qaln1 = pad_aln(qaln_transformed, int(qstart), query_length)
            assert (sum(taln1) == sum(qaln1))
            ta = ''.join((str(c) for c in pad_aln(
                taln_transformed, int(tstart), target_length)))
            qa = ''.join((str(c) for c in pad_aln(
                qaln_transformed, int(qstart), query_length)))

            # out.append([target_seq, query_seq, tstart, tlen, qstart, qlen, score, bitscore, identity, ta, qa])
            out.append([t_ids[int(target_seq)], q_ids[int(query_seq)], tstart,
                       tlen, qstart, qlen, score, bitscore, identity, ta, qa])
    out.sort(key=lambda x: int(x[6]), reverse=True)
    with open(outfile, 'w') as file:
        # file.write('\n'.join(['#tseqnum\tqseqnum\ttstart\ttlen\tqstart\tqlen\tscore\tbitscore\tidentity\ttaln\tqaln'] + ['\t'.join(l) for l in out]))
        file.write('\n'.join(['\t'.join(l) for l in out]))
    print(f"Write {len(out)} matches in {outfile}")
    total += len(out)

print(f"total: {total}")
