"""
Generate heatmaps of cosine similarity map + reference map
Parameters:
- valid_file, valid_matches: Pair of files generated by sequence_matching_db.py
- cached_valid: a cache (could be left empty)
- match_idxs: A list of row indices in valid_matches to plot
"""

import os
import random
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Subset
import torch.nn.functional as F
from torch.amp import GradScaler, autocast
from torch.optim.lr_scheduler import LambdaLR
from torch.utils.tensorboard import SummaryWriter
import datetime
import time
import argparse as ap
from dataset import ValDataset
from pencoder import ColBERT_direct
from constants import max_length, input_dim, latent_dim, hidden_dim, TOKENS, attention_mask_window_size, PAD_TOKEN, blosum62_gttl
from utils import tokens, pad_token
from mds import get_mdsdecmp
import numpy as np
import cv2
import matplotlib.pyplot as plt
plt.rcParams['text.usetex'] = True
device = 'cuda:0' if torch.cuda.is_available() else 'cpu'
base_data = '/scratch/stud2018/ata/ma_data/'
base_ckpts = '/scratch/stud2018/ata/'
base_out = '/scratch/stud2018/ata/'


def make_ref_map2(alnref):
    def make_map(qaln, daln):
        B, n = qaln.shape
        m = torch.zeros((B, n, n), dtype=torch.bool, device=qaln.device)

        # Get indices where qaln and daln are True
        qidxs = torch.nonzero(qaln, as_tuple=False)  # (K, 2) [batch, index]
        didxs = torch.nonzero(daln, as_tuple=False)  # (K, 2)

        assert qidxs.size(0) == didxs.size(0)
        assert torch.all(qidxs[:, 0] == didxs[:, 0])  # batch indices align

        # Unpack indices for advanced assignment
        b = qidxs[:, 0]
        qi = qidxs[:, 1]
        di = didxs[:, 1]

        # Vectorized scatter assignment
        m[b, qi, di] = True
        return m
    return make_map(alnref[:, 0, :], alnref[:, 1, :]).to(device)


def plot_cosine_heatmap(tensor, qheader, theader, save_path="heatmap.png", title="Cosine Similarity Map", isref=False):
    """
    tensor: 2D PyTorch tensor with values in [-1, 1]
    """

    # Move to CPU and convert to numpy
    data = tensor.detach().cpu().numpy()

    # Clamp from [-1, 1] to [0, 1]
    data = np.clip(data, 0, 1)

    # Create figure
    plt.figure(figsize=(8, 6))

    # Plot heatmap
    im = plt.imshow(
        data,
        cmap="gray",     # you can change colormap if you like
        vmin=0,
        vmax=1,
        origin="upper"      # (0,0) at top-left
    )
    if not isref:
        # Add colorbar (reflects clamp 0–1)
        cbar = plt.colorbar(im, shrink=0.3)
        ticks = [0, 0.25, 0.5, 0.75, 1.]
        labels = ["$\\leq 0$", "0.25", "0.5", "0.75", "1"]
        cbar.set_ticks(ticks)
        cbar.set_ticklabels(labels)

    # Ticks (adjust density if large matrix)
    h, w = data.shape
    plt.xticks(np.arange(0, w, 100))
    plt.yticks(np.arange(0, h, 100))

    # Optional: rotate x labels if many
    if w > 10:
        plt.xticks(rotation=90)

    # Labels
    plt.xlabel(qheader)
    plt.ylabel(theader)

    if title:
        plt.title("Map " + title, fontsize=10)

    # Tight layout to avoid cutoff
    plt.tight_layout()

    # Save to PNG
    plt.savefig(save_path, dpi=300)


def check_and_fix_undefined_tensors(model: nn.Module, device=None, init_value=1.0):
    """
    Scans all parameters and buffers in the model for undefined (None) tensors.
    Optionally initializes them to a default tensor to make TorchScript saving possible.

    Args:
        model (nn.Module): the PyTorch model to scan
        device (torch.device, optional): device to initialize tensors on
        init_value (float, optional): default value for initializing undefined tensors

    Returns:
        None
    """
    # Check parameters
    for name, param in model.named_parameters():
        if param is None:
            print(f"[PARAM] {name} is None. Initializing to {init_value}.")
            '''new_param = nn.Parameter(torch.tensor(init_value, dtype=torch.float32))
            if device:
                new_param = new_param.to(device)
            setattr(model, name, new_param)'''

    # Check buffers
    for name, buf in model.named_buffers():
        if buf is None:
            print(f"[BUFFER] {name} is None. Initializing to {init_value}.")
            '''new_buf = torch.tensor(init_value, dtype=torch.float32)
            if device:
                new_buf = new_buf.to(device)
            model.register_buffer(name, new_buf)'''

    print("Scan complete. All undefined tensors have been fixed (if any).")


def load_checkpoint(model, optimizer, scheduler, scaler, path="checkpoint.pth", device="cuda", only_model=False):
    checkpoint = torch.load(path, map_location=device)
    clean_state = {k.replace("_orig_mod.", ""): v for k, v in checkpoint["model_state"].items(
    ) if 'colbert.encoder.pos_encoder' not in k and 'colbert.encoder.encoder' not in k and 'locality_coef' not in k and 'del_per_aa' not in k}
    '''for k in clean_state.keys():
        if 'colbert.encoder.pos_encoder' in k or 'colbert.encoder.encoder' in k:
            del clean_state[k]'''
    model.load_state_dict(clean_state)
    check_and_fix_undefined_tensors(model)
    if not only_model:
        optimizer.load_state_dict(checkpoint["optimizer_state"])
        scheduler.load_state_dict(checkpoint["scheduler_state"])
        scaler.load_state_dict(checkpoint["scaler_state"])
    epoch = checkpoint["epoch"] + 1
    global_step = checkpoint["global_step"]
    print(
        f"Checkpoint loaded from {path}, resuming from epoch {epoch}, step {global_step}")
    return epoch, global_step


def get_model_size(model):
    param_size = 0
    for param in model.parameters():
        # print(param)
        param_size += param.nelement() * param.element_size()
    buffer_size = 0
    for buffer in model.buffers():
        # print(buffer)
        buffer_size += buffer.nelement() * buffer.element_size()
    size_all_mb = (param_size + buffer_size) / 1024**2
    return size_all_mb


def get_model(
        model_ckpts: str,
        model_params: dict
):
    model = ColBERT_direct(
        **model_params
    )
    print('Model size: {:.3f}MB'.format(get_model_size(model)))
    # model = torch.compile(model, mode="default", fullgraph=True)
    trained_epoch, global_step = load_checkpoint(
        model, None, None, None, model_ckpts, device=device, only_model=True)
    model = model.to(device)
    model.eval()
    return model


def main(model):
    '''pairs = [('93218', '780')]
    targets = [int(p[0]) for p in pairs]
    querys = [int(p[1]) for p in pairs]
    target_fasta = base_data + "uniref50_200_512_1m_1_100k.fasta"
    query_fasta = base_data + "uniref50_200_512_1m_0_1k.fasta"
    dataset = TestDataset(query_fasta, target_fasta)'''
    match_idxs = [27483489, 55851334, 22299656, 6439774]
    valid_file = base_data + 'uniref50_1m_1m_01.fasta'
    valid_matches = base_data + 'uniref50_1m_1m_01_matches.h5'
    cached_valid = base_data + "cached_1m_1m_01.h5"
    '''match_idxs = [0, 1]
    valid_file = base_data + 'dataproc_direct.fasta'
    valid_matches = base_data + 'dataproc_direct_matches.h5'
    cached_valid = base_data + "cached_dataproc_direct.h5"'''
    dataset = ValDataset(valid_file, valid_matches, max_length=max_length,
                         h5file=cached_valid, padding=0, index1=True)
    model.eval()
    with torch.no_grad():
        for i, idx in enumerate(match_idxs):
            seq, seqlen, spanref, alnref, _, idx, headers = dataset[idx]
            seq = torch.from_numpy(seq).unsqueeze(0).to(device)
            qlen = int(seqlen[0])
            tlen = int(seqlen[1])
            qheader = headers[0]
            theader = headers[1]
            print(qlen, tlen)
            seqlen = torch.from_numpy(seqlen).unsqueeze(0).to(device)
            seq_padding_mask = (seq == tokens.index(pad_token)).bool()
            spanref = torch.from_numpy(spanref).unsqueeze(0).to(device)
            alnref = torch.from_numpy(alnref).unsqueeze(0).to(device)
            ref_map = make_ref_map2(alnref)
            ref_map = ref_map[:, :qlen, :tlen]
            with autocast(device_type='cuda', dtype=torch.float16):
                maps = model(seq, seq_padding_mask, 1).squeeze(
                    0).squeeze(0).detach().cpu()
                maps = maps[:qlen, :tlen]
                plot_cosine_heatmap(maps, qheader, theader, save_path=base_out +
                                    f"img/{i}.png", title=f"{qheader}_{theader}", isref=False)
                plot_cosine_heatmap(ref_map.squeeze(0), qheader, theader, save_path=base_out +
                                    f"img/{i}_ref.png", title=f"{qheader}_{theader} Reference", isref=True)


if __name__ == "__main__":
    model_ckpts = base_ckpts + 'ckpts.pth'
    model_params = {
        'dims': [[32, 96, 160, 256, 320, 384, 480]],
        'conv_kernels': [[3, 5, 7, 9, 11, 15, 17]],
        'dilations': [[1, 2, 3, 4, 5, 6, 7]],
        'enc_type': 0,
        'init_token': None,  # get_mdsdecmp(),
        'guide_blosum': torch.tensor(blosum62_gttl, dtype=torch.float32),
        'knn': 5,
        'sigma': None,
        'normalized': True,
        'outdims': [320],
        'skip': False,
        'ptwise': True,
        'extracts': [[0, 2, 4, 6]],
    }
    model = get_model(model_ckpts=model_ckpts, model_params=model_params)
    main(model)
