"""
Plot program run time by varying a parameters while keeping other fixed. Use cache generated by benchmark_pr_ivfpq.py
"""

from pathlib import Path
import re
import matplotlib.pyplot as plt
import numpy as np


def parse_file(file_path):
    steps_time = []
    whole_time = []
    with open(file_path, 'r') as handler:
        for line in handler:
            if len(steps_time) >= 2 and len(whole_time) >= 6:
                break
            if line.startswith("#Time:\t"):
                steps_time.append(
                    float(re.search(r"(-?\d+\.?\d*?)", line).group(1)))
            elif line.startswith("# TIME\t"):
                whole_time.append(
                    float(re.search(r"(-?\d+\.?\d*?)", line).group(1)))
    data = {
        "Import Index": whole_time[0],
        "Encode Sequences": steps_time[0],
        "Query Sequences": steps_time[1],
        "Assemble Alignments": sum(whole_time[2:])
    }
    return data


def plot(data, labels, ax):
    print(labels)
    sample_key = list(data.keys())[0]
    bottom = np.zeros(len(data[sample_key]))
    for l, d in data.items():
        ax.bar(labels, d, 0.5, label=l, bottom=bottom)
        bottom += d
    # ax.set_xticklabels(labels)
    ax.set_xlabel("Configuration")
    ax.set_ylabel("Run time (ms)")
    ax.set_title("Fixed $k=128, s_{min}=0.6$")


fig, ax = plt.subplots()
fig.set_figwidth(12)
fig.set_figheight(6)
file_list = list(Path(
    "/scratch/stud2018/ata/measurements2/cache/").glob("out_ivfpq_8192_128_0.600_3_3_*.tsv"))
file_list.sort(key=lambda f: int(f.name[:-4].split("_")[3]))
data = {}
labels = []
for i, file in enumerate(file_list):
    split = file.name[:-4].split("_")
    k = int(split[3])
    t = float(split[4])
    tolerance = int(split[5])
    len_bound = int(split[6])
    nprobe = int(split[7])
    d = parse_file(file)
    for key in d:
        if key not in data:
            data[key] = []
        data[key].append(d[key])
    labels.append(f"{k}, {t:.1f}, {nprobe}")
plot(data, labels, ax)
plt.legend()
plt.tight_layout()
plt.savefig("/scratch/stud2018/ata/measurements2/runtime_fixedkt.png")
