"""
compute precision/recall of ProtSearchIVFPQ against a SW reference
- ss_file: result file generated by running ProtSearchIVFPQ
- sw_file: result file generated using gttl_parser.py
"""

import sys
# from scipy import stats
# from sklearn.metrics import jaccard_score
# import numpy as np
# import tables as tb

ss_file = sys.argv[1]
sw_file = sys.argv[2]

with open(ss_file, 'r') as handler:
    ss_data = [line[:-1].split("\t") for line in list(handler)[41:]]

with open(sw_file, 'r') as handler:
    sw_data = [line[:-1].split("\t") for line in list(handler)]

ss_seqpair_set = set((e[0], e[1]) for e in ss_data)
sw_seqpair_set = set((e[0], e[1]) for e in sw_data)

# ss_dict = {(e[0], e[1]) : [float(v) for v in e[2:-2]] + e[-2:] for e in ss_data}
# sw_dict = {(e[0], e[1]) : [float(v) for v in e[2:-2]] + e[-2:] for e in sw_data}

intersection = ss_seqpair_set.intersection(sw_seqpair_set)
print("Recall: ", len(intersection) / len(sw_seqpair_set))
print("Precision: ", len(intersection) / len(ss_seqpair_set))

'''ss_filtered = {}
sw_filtered = {}

ss_dict_filtered = {k: ss_dict[k] for k in intersection}
sw_dict_filtered = {k: sw_dict[k] for k in intersection}

res = stats.pearsonr([e[5-2] for e in ss_dict_filtered.values()], [e[6-2] for e in sw_dict_filtered.values()])
print(res.statistic, res.pvalue)

s = 0
for k,v in sw_dict_filtered.items():
    s += jaccard_score([int(c) for c in v[-1]], [int(c) for c in ss_dict_filtered[k][-1]])
    s += jaccard_score([int(c) for c in v[-2]], [int(c) for c in ss_dict_filtered[k][-2]])
print(s / len(sw_dict_filtered) / 2)

diff_set = sw_seqpair_set.difference(ss_seqpair_set)
dtype = np.dtype([
    ('u1', 'u4'),
    ('u2', 'u4'),
    ('u3', 'u4'),
    ('u4', 'u4'),
    ('u5', 'u4'),
    ('u6', 'u4'),
    ('u7', 'u8'),
    ('str1_bits', np.uint8, (64,)),
    ('str2_bits', np.uint8, (64,)),
])
diff_set_size = len(diff_set)
mat = np.recarray((diff_set_size,),dtype=dtype)

for i, (target_seqnum, query_seqnum) in enumerate(diff_set):
    entry = sw_dict[(target_seqnum, query_seqnum)]
    ts, te, qs, qe =  int(entry[0]), int(entry[0]) + int(entry[1]), int(entry[2]), int(entry[2]) + int(entry[3])
    mat[i]['u1'] = int(target_seqnum)
    mat[i]['u2'] = int(query_seqnum) + 10000
    mat[i]['u3'] = ts + 1
    mat[i]['u4'] = te
    mat[i]['u5'] = qs + 1
    mat[i]['u6'] = qe
    mat[i]['u7'] = int(entry[4])
    mat[i]['str1_bits'] = np.packbits(np.array([c == "1" for c in entry[-2]] + [0] * (512 - len(entry[-2])),dtype=bool))
    mat[i]['str2_bits'] = np.packbits(np.array([c == "1" for c in entry[-1]] + [0] * (512 - len(entry[-1])),dtype=bool))

def write(outfile, data):
    aln_h5f = tb.open_file(outfile,"a")
    table = aln_h5f.create_table('/', 'aln_data', description=dtype, title="ALN Table")
    #for i, (q_idx, qaln_data) in enumerate(intdata.items()):
    table.append(data)
    aln_h5f.close()

outfile = sys.argv[3]
write(outfile, mat)'''

# ./sw_all_against_all.x -d ../../../masterarbeit-anhvietta/data/tmp_10000_target.fasta -q ../../../masterarbeit-anhvietta/data/tmp_100_query.fasta -v 2 -c 47 -t 6 -a 4+512 -o ../../../masterarbeit-anhvietta/swref/100_10000/out
