"""
A simple logistic regression model to test the discrimination between false positives and true positives. Use 2 tsv files generated by false_positives.py
"""

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import numpy as np

dtype = np.dtype([
    ('idt', 'u4'),
    ('idq', 'u4'),
    ('f1', 'f4'),
    ('f2', 'f4'),
    ('f3', 'f4'),
    ('f4', 'f4'),
    ('f5', 'f4'),
    ('f6', 'f4'),
    ('y', '?')
])


def load_data(f, istp):
    with open(f, "r") as handler:
        data = [line.strip().split("\t") for line in handler]
        data = [[float(a) for a in d] + [istp] for d in data]
        data = [tuple(d) for d in data]
        data = np.array(data, dtype=dtype)
    return data


tp = load_data("/scratch/stud2018/ata/measurements2/tp.tsv", True)
fp = load_data("/scratch/stud2018/ata/measurements2/fp.tsv", False)

feature_names = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6']
data = np.concatenate([tp, fp])

X = np.column_stack([data[name] for name in feature_names])
y = data['y']
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y
)

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_val)

print(classification_report(y_val, y_pred))
'''
probs = model.predict_proba(X_val)[:, 1]

threshold = 0.3  # lower → higher sensitivity
y_pred = (probs > threshold).astype(int)
'''
